
---
- name: Create user group managent with collab directory
  hosts: all
  become: yes
  vars:
    dev_group: "developer"
    dev_user:
      - mario
      - mike
    shared_dir: "/share/devops_project"

  tasks:
    - name: Create a group
      ansible.builtin.group:
        name: "{{ dev_group }}"
        state: present

    - name: Create users
      ansible.builtin.user: 
        name: "{{ item }}"
        groups: "{{ dev_group }}"
        append: yes
        password_expire_max: 0
      loop: "{{ dev_user }}"

    - name: Create a collab directory
      ansible.builtin.file:
        path: "{{ shared_dir }}"
        owner: root
        group: "{{ dev_group }}"
        mode: '0770'
        state: directory
         
