
---
- name: webservers
  hosts: all
  become: yes

  tasks:
    - name: Create a group
      group:
        name: automation
        state: present

    - name: Create a user
      user:
        name: developer
        groups: automation
        append: yes

    - name: Package management
      dnf:
        name:
          - httpd
          - mod_ssl
        state: latest


    - name: Deploy apache
      ansible.builtin.template:
        src:  ./tempaltes/vhost.conf.j2
        dst: /etc/httpd/conf.d/vhost.conf
        ower: root
        group: root
        mode: '0644'
      notify:
        - Restart apache



