---
- name: Install apache
  hosts: all 
  become: yes

  vars:
    apache_port: 8080
  
  tasks:
    - debug:
        msg: "{{ apache_port }}"

    - name: start
      service:
        name: httpd
        state: started
        enabled: yes
        
