---
- name: Install http, and enable it
  hosts: all 
  become: yes

  vars:
    apache_port: 8080
  
  tasks:
    - debug:
        msg: "{{ apache_port }}"

    - name: start
     ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
        
