
---
- name: Block, rescue and always
  hosts: all
  become: true

  tasks:
    - block:
        - name: Create a file /bin path
          ansible.builtin.command: /usr/bin/false

      rescue:
        - name: Display a message
          ansible.builtin.debug:
            msg: Configuration deployment failed 

      always:
        - name: run this always
          ansible.builtin.debug:
            msg: Configuration task complete
    
