
---
- name: Gather system info
  hosts: all
  become: true

  tasks:
    - name: Gather system's info
      ansible.builtin.template:
        src: report.txt.j2
        dest: "/reports/{{ inventory_hostname }}.txt"
        owner: root
        group: root
        mode: '644'
      delegate_to: localhost
      run_once: true
      when: ansible_facts['distribution'] == "Rocky"

